name: Build and Deploy to GCE

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCE
        run: |
          # Replace this with your deployment commands
          ssh -o StrictHostKeyChecking=no -i $SSH_AUTH_SOCK shivamsharma2002@34.131.8.203 'bash -s' << 'ENDSSH'
            cd repo/cookoff-backend
            sudo docker compose down
            git pull origin main
            sudo docker compose up --build -d --scale node-app=2
            # Other deployment commands
          ENDSSH
